version: '3.8'

services:
  app:
    build: .
    ports:
      - "8098:8098"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/careertracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - career-net

  db:
    image: postgres:15
    container_name: postgres-career
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=careertracker
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - career-net

volumes:
  postgres_data:

networks:
  career-net:
    driver: bridge