spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "${RAILWAY_STATIC_URL:http://localhost:8080}/login/oauth2/code/github"

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always