spring:
  datasource:
    url: jdbc:postgresql://dpg-d20oedripnbc73dgh84g-a.oregon-postgres.render.com/careertracker
    username: careertracker_user
    password: FzPIZKkcUuM9d8zb1bei5cuHdjTQoPuq
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "https://api-work-profile.onrender.com/login/oauth2/code/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always