spring:
  application:
    name: work-profile-portal
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    driver-class-name: org.postgresql.Driver
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
    show-summary: false
    show-summary-output: LOG
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email,repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  mvc:
    hidden method:
          filter:
            enabled: true

server:
  port: 8098

github:
  token: ${GITHUB_TOKEN}
  base-url: https://api.github.com

recaptcha:
  site-key: ${RECAPTCHA_SITE_KEY:6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}
  secret-key: ${RECAPTCHA_SECRET_KEY:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}
  verify-url: https://www.google.com/recaptcha/api/siteverify

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.thymeleaf: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    feign: WARN
    liquibase: ERROR
    liquibase.database: ERROR
    liquibase.executor: ERROR
    liquibase.changelog: ERROR
    liquibase.hub: OFF
    liquibase.analytics: OFF
