spring:
  datasource:
    url: jdbc:postgresql://dpg-d20oedripnbc73dgh84g-a:5432/careertracker
    username: careertracker_user
    password: FzPIZKkcUuM9d8zb1bei5cuHdjTQoPuq
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://dpg-d20oedripnbc73dgh84g-a:5432/careertracker
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "https://api-work-profile.onrender.com/login/oauth2/code/github"
            client-id: Ov23li1tI16Hb3jbYl3c
            client-secret: dc343ab563dfc795fa14cfab04d9d6356d28b0b3
            scope: user:email,repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: strict
  forward-headers-strategy: framework
  use-forward-headers: true
  error:
    include-stacktrace: never
    include-message: never

github:
  token: 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
  base-url: https://api.github.com

app:
  base-url: https://api-work-profile.onrender.com
  api:
    key: ${API_KEY:}

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"