spring:
  application:
    name: work-profile-portal
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:railway}
  
  datasource:
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
    show-summary: false
    show-summary-output: LOG
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email,repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
  forward-headers-strategy: native
  error:
    include-stacktrace: never
    include-message: never

github:
  token: ${GITHUB_TOKEN:}
  base-url: https://api.github.com

app:
  api:
    key: ${API_KEY:}

recaptcha:
  site-key: ${RECAPTCHA_SITE_KEY:6Ld5II0rAAAAAMWEG_C5w3egPB9s7AsOyKxU6_JH}
  secret-key: ${RECAPTCHA_SECRET_KEY:6Ld5II0rAAAAALiw95tI0GNYUDtfQTN6JwiDdPnP}
  verify-url: https://www.google.com/recaptcha/api/siteverify

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.thymeleaf: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    feign: WARN
    liquibase: ERROR
    liquibase.database: ERROR
    liquibase.executor: ERROR
    liquibase.changelog: ERROR
    liquibase.hub: OFF
    liquibase.analytics: OFF
