spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/careertracker}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  liquibase:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/careertracker}
    user: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "https://api-work-profile.onrender.com/login/oauth2/code/github"

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: strict
  forward-headers-strategy: framework
  use-forward-headers: true
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  api:
    key: ${API_KEY}