spring:
  datasource:
    url: ${RDS_HOSTNAME:jdbc:postgresql://localhost:5432/careertracker_staging}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

logging:
  file:
    name: /var/log/work-profile-staging.log