spring:
  application:
    name: work-profile-portal
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:54322/careertracker}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email,repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
  mvc:
    hidden method:
          filter:
            enabled: true

server:
  port: 8098

github:
  token: ${GITHUB_TOKEN}
  base-url: https://api.github.com

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.thymeleaf: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    feign: WARN
