spring:
  datasource:
    url: jdbc:postgresql://dpg-d20oedripnbc73dgh84g-a.oregon-postgres.render.com/careertracker
    username: careertracker_user
    password: FzPIZKkcUuM9d8zb1bei5cuHdjTQoPuq
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

BASE_URL: https://api-work-profile.onrender.com

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: strict
  forward-headers-strategy: native
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.hibernate: WARN