spring:
  datasource:
    url: jdbc:postgresql://dpg-d20oedripnbc73dgh84g-a.oregon-postgres.render.com/careertracker
    username: careertracker_user
    password: FzPIZKkcUuM9d8zb1bei5cuHdjTQoPuq
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li1tI16Hb3jbYl3c
            client-secret: ac3fd8bddb8419d6513f07521aa6357177f5d821
            redirect-uri: https://api-work-profile.onrender.com/login/oauth2/code/github
            scope: user:email,repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

BASE_URL: https://api-work-profile.onrender.com

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: strict
  forward-headers-strategy: native
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
