spring:
  datasource:
    url: jdbc:postgresql://dpg-d20oedripnbc73dgh84g-a.oregon-postgres.render.com/careertracker
    username: careertracker_user
    password: FzPIZKkcUuM9d8zb1bei5cuHdjTQoPuq
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "${BASE_URL:https://api-work-profile.onrender.com}/login/oauth2/code/github"
            scope: user:email,repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: none
  forward-headers-strategy: framework
  use-forward-headers: true
  error:
    include-stacktrace: never
    include-message: never

# Configuração da URL base
app:
  base-url: ${BASE_URL:https://api-work-profile.onrender.com}

logging:
  level:
    api.work.profile: INFO
    api.work.profile.service.CustomOAuth2UserService: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
