spring:
  datasource:
    url: ${RDS_HOSTNAME:jdbc:postgresql://localhost:5432/careertracker}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "https://devportal.com.br/login/oauth2/code/github"

server:
  port: ${PORT:5000}
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        secure: true
        same-site: strict
  error:
    include-binding-errors: never

logging:
  level:
    api.work.profile: WARN
    org.springframework.security: ERROR
    org.springframework.web: ERROR
    org.thymeleaf: ERROR
    org.hibernate: ERROR
    feign: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/work-profile.log
    max-size: 10MB
    max-history: 30