spring:
  datasource:
    url: ${RDS_HOSTNAME:jdbc:postgresql://localhost:5432/careertracker_staging}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
  
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "https://api-work-profile.onrender.com/login/oauth2/code/github"

server:
  port: ${PORT:8080}

logging:
  file:
    name: /var/log/work-profile-staging.log