spring:
  datasource:
    url: ${RDS_HOSTNAME:jdbc:postgresql://localhost:5432/careertracker_staging}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
  
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li1tI16Hb3jbYl3c
            client-secret: dc343ab563dfc795fa14cfab04d9d6356d28b0b3
            redirect-uri: "https://api-work-profile.onrender.com/login/oauth2/code/github"

server:
  port: ${PORT:8080}

logging:
  file:
    name: /var/log/work-profile-staging.log