spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/careertracker
    username: postgres
    password: postgres
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    
logging:
  level:
    api.work.profile: DEBUG
    liquibase: DEBUG