spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  
  security:
    oauth2:
      client:
        registration:
          github:
            redirect-uri: "${RAILWAY_STATIC_URL}/login/oauth2/code/github"

server:
  port: ${PORT:8080}
  compression:
    enabled: true
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: true
        same-site: strict
  forward-headers-strategy: native
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    api.work.profile: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

app:
  api:
    key: ${API_KEY}